name: Documentation Tests
on: [pull_request]

jobs:
  vale-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        with:
          vale_flags: "--glob=*.md"
          files: _onlyModified
          onlyAnnotateModifiedLines: true
